if (NOT CROSS_COMPILE AND NOT FEATURE_EMULATOR)
	SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CROSS_COMPILE arm-none-eabi-)
endif()

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

set(CMAKE_ASM_COMPILER ${CROSS_COMPILE}gcc)
set(CMAKE_AR ${CROSS_COMPILE}ar)
set(CMAKE_RANLIB ${CROSS_COMPILE}ranlib)
set(CMAKE_C_COMPILER ${CROSS_COMPILE}gcc)
set(CMAKE_CXX_COMPILER ${CROSS_COMPILE}g++)
set(CMAKE_LINKER ${CROSS_COMPILE}g++)
set(CMAKE_OBJCOPY ${CROSS_COMPILE}objcopy)
set(CMAKE_SIZE ${CROSS_COMPILE}size)

set(TOOLCHAIN gcc)
string(TOUPPER ${TOOLCHAIN} TOOL_U)

add_compile_definitions(
    ${TOOLCHAIN}
    ${TOOL_U}
)

set(ARCH ARM_CM4F)